### ISSUE TITLE
ChainedSigV4PropertiesProvider does not allow AWS credentials from the DefaultAWSCredentialsProviderChain

### ISSUE THREAD

**Issue by crosleyj** [aws/amazon-neptune-gremlin-java-sigv4#22]
I want to use the DefaultAWSCredentialsProviderChain to call Neptune, but this appears to be impossible because during the construction the credentials provider the credentials are required in the environment or system variables.

* The AwsSigV4ClientHandshaker uses the DefaultAWSCredentialsProviderChain here: https://github.com/aws/amazon-neptune-gremlin-java-sigv4/blob/953c407235c687cd6705834708f8022b527c1b64/src/main/java/com/amazon/neptune/gremlin/driver/sigv4/AwsSigV4ClientHandshaker.java#L89

* However, during the construction of the AwsSigV4ClientHandshaker (here: https://github.com/aws/amazon-neptune-gremlin-java-sigv4/blob/953c407235c687cd6705834708f8022b527c1b64/src/main/java/org/apache/tinkerpop/gremlin/driver/SigV4WebSocketChannelizer.java#L204) the ChainedSigV4PropertiesProvider is constructed, and the constructor (here: https://github.com/aws/amazon-neptune-gremlin-java-sigv4/blob/master/src/main/java/com/amazon/neptune/gremlin/driver/sigv4/ChainedSigV4PropertiesProvider.java#L42) tries to fetch the credentials only from the system or environment variables, which means these would be required to be set.

**Comment by floschmedding** [comment]
Hi crosleyj,
I think using [DefaultAWSCredentialsProviderChain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) works for the credentials. It's only the [parameter SERVICE_REGION](https://docs.aws.amazon.com/neptune/latest/userguide/iam-auth-connecting-gremlin-console.html) that needs to be provided as environment or system variable. Would that work for your use case?
Best regards,
Florian

**Comment by 00linglin** [comment]
@floschmedding can we add AWS_REGION as well instead of just looking for SERVICE_REGION, in Lambda AWS_REGION is pre-populated

**Comment by crosleyj** [comment]
SERVICE_REGION worked for me, but I am indeed using Lambda so AWS_REGION would be nice to have too

**Comment by floschmedding** [comment]
Thanks for the updates and the feedback! We track usage of AWS_REGION in https://github.com/aws/amazon-neptune-gremlin-java-sigv4/issues/23, so I'm closing this issue.
