### ISSUE TITLE
Adapt for https://issues.apache.org/jira/browse/TINKERPOP-2369

### ISSUE THREAD

**Issue by DukeDai** [aws/amazon-neptune-gremlin-java-sigv4#29]
Hi, 

gremlin has released 3.4.9 for https://issues.apache.org/jira/browse/TINKERPOP-2369 for IAM token expire periodically. 
Any plan for the enhancement in sigv4 library so that others won't maintain separately.

**Comment by divijvaidya** [comment]
Hello @DukeDai 

Thank you for pointing this out. Yes, we are going to upgrade this library to use TinkerPop 3.4.9 as a dependency.

Currently, we are in the process of testing 3.4.9 client with Neptune for regressions and sanity. Once we have conducted the testing internally, we would upgrade the dependency here.

Thank you for your patience. Let us know if this is blocking you in any manner.

**Comment by DukeDai** [comment]
Thank you for the update, @divijvaidya 

Somehow it's a blocker(we need a lot of retries to avoid the unpredictable token expire, or other ugly workaround). 

If you have pre/beta release, we would like to apply and verify.

**Comment by divijvaidya** [comment]
Hello @DukeDai 

I have upgraded the TinkerPop version for this package to 3.4.9. I will publish the artifact to Maven repo after our internal testing is complete.

Meanwhile, you can checkout this package from tip of master or from tag 2.1.2 to use the latest version.
