### ISSUE TITLE
HANDSHAKE_TIMEOUT_MILLIS Issue

### ISSUE THREAD

**Issue by okulkarni-eis** [aws/amazon-neptune-gremlin-java-sigv4#4]
Hello,

In class 'SigV4WebSocketChannelizer' on line 103 you have mentioned following line:
 private static final int HANDSHAKE_TIMEOUT_MILLIS = 1500;

On line 188, you mention this 'if the handshake takes longer 15 seconds' where you are using 1500 milis. This is in fact 1.5 seconds and not 15 seconds. I am getting timeout issues because of this.

**Comment by kunallanuk** [comment]
Thanks for bringing this up. I have published the fix with this commit - https://github.com/aws/amazon-neptune-sigv4-signer/commit/ccf649e5cfbcd37ca71745755dc728d8da2323b3

**Comment by okulkarni-eis** [comment]
Sure thing.
